apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-monitoring
  namespace: argocd
spec:
  source:
    path: kube-monitoring
    repoURL: https://github.com/godtolo/k3s-stack.git
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-monitoring
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
