apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
spec:
  destination:
    namespace: uptime-kuma
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/uptime-kuma
    repoURL: 'https://github.com/dirsigler/uptime-kuma-helm.git'
    targetRevision: HEAD
  sources: []
  project: default

