apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linktree-web-prod
  namespace: argocd
spec:
  destination:
    namespace: linktree-web-prod
    server: 'https://kubernetes.default.svc'
  source:
    path: manifest
    repoURL: 'https://github.com/godtolo/linktree_infra.git'
    targetRevision: HEAD
  sources: []
  project: default
