apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linktree-web-prod
  namespace: argocd
spec:
  source:
    path: manifest
    repoURL: 'https://github.com/godtolo/linktree_infra.git'
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    namespace: linktree-web-prod
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
