apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-1710211055
  namespace: kube-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: grafana
      app.kubernetes.io/instance: grafana-1710211055
      app.kubernetes.io/name: grafana
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: grafana
        app.kubernetes.io/instance: grafana-1710211055
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: grafana
        app.kubernetes.io/version: 10.3.3
        helm.sh/chart: grafana-9.13.0
      annotations:
        checksum/config: 7a3941d0a42abcb0d0b9751efd4bfd79376c8c0a7623e39128c3cce734c5b65d
        checksum/dashboard-provider: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b
        checksum/secret: 4f36d05e0550a19c5b52972dbaa1feef05dbcea3fc9995b26873ace812fc99cd
    spec:
      volumes:
      - name: empty-dir
        emptyDir: {}
      - name: data
        persistentVolumeClaim:
          claimName: grafana-1710211055
      containers:
      - name: grafana
        image: docker.io/bitnami/grafana:10.3.3-debian-12-r5
        ports:
        - name: dashboard
          containerPort: 3000
          protocol: TCP
        envFrom:
        - configMapRef:
            name: grafana-1710211055-envvars
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana-1710211055-admin
              key: GF_SECURITY_ADMIN_PASSWORD
        resources: {}
        volumeMounts:
        - name: empty-dir
          mountPath: /tmp
          subPath: tmp-dir
        - name: empty-dir
          mountPath: /opt/bitnami/grafana/conf
          subPath: app-conf-dir
        - name: empty-dir
          mountPath: /opt/bitnami/grafana/tmp
          subPath: app-tmp-dir
        - name: data
          mountPath: /opt/bitnami/grafana/data
        livenessProbe:
          httpGet:
            path: /api/health
            port: dashboard
            scheme: HTTP
          initialDelaySeconds: 120
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /api/health
            port: dashboard
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 6
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            drop:
            - ALL
          privileged: false
          runAsUser: 1001
          runAsGroup: 0
          runAsNonRoot: true
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: grafana-1710211055
      serviceAccount: grafana-1710211055
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: Always
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: grafana
                  app.kubernetes.io/instance: grafana-1710211055
                  app.kubernetes.io/name: grafana
              topologyKey: kubernetes.io/hostname
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
