apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-1710211055-envvars
  namespace: kube-monitoring
data:
  GF_AUTH_LDAP_ALLOW_SIGN_UP: 'false'
  GF_AUTH_LDAP_CONFIG_FILE: /opt/bitnami/grafana/conf/ldap.toml
  GF_AUTH_LDAP_ENABLED: 'false'
  GF_INSTALL_PLUGINS: ''
  GF_PATHS_CONFIG: /opt/bitnami/grafana/conf/grafana.ini
  GF_PATHS_DATA: /opt/bitnami/grafana/data
  GF_PATHS_LOGS: /opt/bitnami/grafana/logs
  GF_PATHS_PLUGINS: /opt/bitnami/grafana/data/plugins
  GF_PATHS_PROVISIONING: /opt/bitnami/grafana/conf/provisioning
  GF_SECURITY_ADMIN_USER: admin
