apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-prometheus-1710214099-node-exporter
  namespace: kube-monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: kube-prometheus-1710214099
      app.kubernetes.io/name: node-exporter
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kube-prometheus-1710214099
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: node-exporter
        app.kubernetes.io/version: 1.7.0
        helm.sh/chart: node-exporter-3.16.0
    spec:
      volumes:
      - name: empty-dir
        emptyDir: {}
      - name: proc
        hostPath:
          path: /proc
          type: ''
      - name: sys
        hostPath:
          path: /sys
          type: ''
      containers:
      - name: node-exporter
        image: docker.io/bitnami/node-exporter:1.7.0-debian-12-r12
        args:
        - '--path.procfs=/host/proc'
        - '--path.sysfs=/host/sys'
        - '--web.listen-address=0.0.0.0:9200'
        - >-
          --collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)$
        - >-
          --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+)($|/)
        ports:
        - name: metrics
          hostPort: 9200
          containerPort: 9200
          protocol: TCP
        resources: {}
        volumeMounts:
        - name: empty-dir
          mountPath: /tmp
          subPath: tmp-dir
        - name: proc
          readOnly: true
          mountPath: /host/proc
        - name: sys
          readOnly: true
          mountPath: /host/sys
        livenessProbe:
          httpGet:
            path: /
            port: metrics
            scheme: HTTP
          initialDelaySeconds: 120
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /
            port: metrics
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 6
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            drop:
            - ALL
          privileged: false
          runAsUser: 1001
          runAsGroup: 0
          runAsNonRoot: true
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: kube-prometheus-1710214099-node-exporter
      serviceAccount: kube-prometheus-1710214099-node-exporter
      automountServiceAccountToken: false
      hostNetwork: true
      hostPID: true
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: Always
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: kube-prometheus-1710214099
                  app.kubernetes.io/name: node-exporter
              topologyKey: kubernetes.io/hostname
      schedulerName: default-scheduler
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  revisionHistoryLimit: 10
